#include<stdio.h>
char s[2][500],a[500];
int main()
{
	int t,n,i,curr,x;
	scanf("%d",&t);
	while(t)
	{
		scanf("%d",&n);
		scanf("%s",a);
		for(i=0;i<n;i++)
		s[0][i]=a[i];
		scanf("%s",a);
		for(i=0;i<n;i++)
		s[1][i]=a[i];
		i=0;
		while((i<n)&&(s[0][i]=='.')&&(s[1][i]=='.'))
		i++;
		if(i<n)
		{
			if((s[0][i]=='#')&&(s[1][i]=='#'))
			{
				x=i;
				curr=0;
				while(i<n)
				{
					if((s[0][i]=='#')&&(s[1][i]=='#'))
					{
						if(curr==0)
						curr=1;
						else
						curr=0;
						i++;
					}
					else if((s[0][i]=='.')&&(s[1][i]=='.'))
					{
						i++;
						while((i<n)&&(s[0][i]=='.')&&(s[1][i]=='.'))
						i++;
						if(i!=n)
						break;
					}
					else
					{
						if(s[curr][i]=='#')
						i++;
						else
						break;
					}
				}
				if(i!=n)
				{
					i=x;
					curr=1;
					while(i<n)
				{
					if((s[0][i]=='#')&&(s[1][i]=='#'))
					{
						if(curr==0)
						curr=1;
						else
						curr=0;
						i++;
					}
					else if((s[0][i]=='.')&&(s[1][i]=='.'))
					{
						i++;
						while((i<n)&&(s[0][i]=='.')&&(s[1][i]=='.'))
						i++;
						if(i!=n)
						break;
					}
					else
					{
						if(s[curr][i]=='#')
						i++;
						else
						break;
					}
				}
				}
			}
			else
			{
				if(s[0][i]=='#')
				curr=0;
				else
				curr=1;
				while(i<n)
				{
					if((s[0][i]=='#')&&(s[1][i]=='#'))
					{
						if(curr==0)
						curr=1;
						else
						curr=0;
						i++;
					}
					else if((s[0][i]=='.')&&(s[1][i]=='.'))
					{
						i++;
						while((i<n)&&(s[0][i]=='.')&&(s[1][i]=='.'))
						i++;
						if(i!=n)
						break;
					}
					else
					{
						if(s[curr][i]=='#')
						i++;
						else
						break;
					}
				}
			}
        }
        if(i==n)
        printf("yes\n");
        else
        printf("no\n");
		t--;
	}
}
