#include <bits/stdc++.h>
using namespace std;
int seet[2500][2501],a[2500];
int main()
{
	int t,n,k,i,j,l,ans,index1,index2,flag;
	cin>>t;
	while(t)
	{
		cin>>n>>k;
		for(i=0;i<n;i++)
		{
			cin>>seet[i][0];
			for(j=0;j<seet[i][0];j++)
			cin>>a[j];
			sort(a,a+seet[i][0]);
			for(j=0;j<seet[i][0];j++)
			seet[i][j+1]=a[j];
		}
		ans=0;
		for(i=0;i<(n-1);i++)
		{
			if(seet[i][0]>=k)
			ans=ans+(n-i-1);
			else
			{
				for(j=i+1;j<n;j++)
				{
					flag=0;
					if(seet[j][0]>=k)
					ans++;
					else
					{
						if((seet[i][0]+seet[j][0])<k);
						else
						{
							for(l=1,index1=1,index2=1;(l<=k)&&(index1<=seet[i][0])&&(index2<=seet[j][0]);l++)
							{
								if((seet[i][index1]==l)&&(seet[j][index2]==l))
								{
									index1++;
									index2++;
								}
								else
								{
									if((seet[i][index1]!=l)&&(seet[j][index2]!=l))
									{
										flag=1;
										break;
									}
									else
									{
										if(seet[i][index1]==l)
										index1++;
										else
										index2++;
									}
								}
							}
							if(flag==1);
							else
							{
								for(;(l<=k)&&(index1<=seet[i][0]);l++)
								{
									if(seet[i][index1]==l)
									index1++;
									else
									{
										flag=1;
										break;
									}
								}
								if(flag==1);
								else
								{
									for(;(l<=k)&&(index2<=seet[j][0]);l++)
									{
										if(seet[j][index2]==l)
										index2++;
										else
										{
											break;
										}
									}
									if(l==(k+1))
									ans++;
								}
							}
						}
					}
				}
			}
		}
		cout<<ans<<endl;
		t--;
	}
	return 0;
}
